DROP TABLE IF EXISTS user_movies CASCADE;
DROP TABLE IF EXISTS movies CASCADE;
DROP TABLE IF EXISTS users CASCADE;


CREATE TABLE users (
	id SERIAL PRIMARY KEY NOT NULL,
	first_name VARCHAR(50) NOT NULL,
  last_name VARCHAR(50) NOT NULL,
  email VARCHAR(255) NOT NULL,
  password VARCHAR(255)
);

CREATE TABLE movies (
	id SERIAL PRIMARY KEY NOT NULL,
	imdbID VARCHAR(50) NOT NULL,
	name VARCHAR(50) NOT NULL,
  poster VARCHAR(255) NOT NULL,
	rating INTEGER DEFAULT 0
);

CREATE TABLE user_movies (
	id SERIAL PRIMARY KEY NOT NULL,
	user_id INTEGER REFERENCES users(id),
	movie_id INTEGER REFERENCES movies(id),
	rating INTEGER DEFAULT 0
);





